### ISSUE TITLE
Let's get this issue train started

### ISSUE THREAD

**Issue by NotWeeb** [deprilula28/Hikaru#3]
fix ur repo pls
![image](https://user-images.githubusercontent.com/29748817/82741229-abb07900-9d82-11ea-9fa6-e4284452590e.png)

**Comment by deprilula28** [comment]
how is this #3

**Comment by NotWeeb** [comment]
github be like that for some reason

**Comment by Cyber28** [comment]
dep, why?

**Comment by deprilula28** [comment]
im not even sure what the issue is lmao
